services:
  - type: web
    name: investment-calculator
    env: python
    plan: free
    region: oregon
    repoRoot: /project/src
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: investment_insights
          property: connectionString
      - key: SECRET_KEY
        value: 4334d7b0d850e8426d75728257271d46
      - key: PYTHON_VERSION
        value: 3.9
databases:
  - name: investment_insights
    plan: free
    region: oregon