# -*- coding: utf-8 -*-
# YIAP Practise Questions -- question bank sourced from
# "Reading Financial Statements: MTN Ghana FY2025" (YIN Ghana Financial Statements
# Masterclass, Merban Capital Limited, 14 July 2026).
# All figures are Scancom PLC (MTN Ghana) FY2025 audited Group results, GHS'000 unless stated.

INCOME_STATEMENT_QUESTIONS = [
    # Chapter 1: What the Income Statement Is
    {"chapter": "What the Income Statement Is", "chapter_num": 1, "question": "The income statement is also known by which other names?", "a": "Statement of Cash Flows / Cash Book", "b": "Statement of Financial Position / Balance Sheet", "c": "Statement of Comprehensive Income / Profit & Loss / P&L", "d": "Statement of Changes in Equity", "answer": "c", "explanation": "The masterclass lists Statement of Comprehensive Income, Profit & Loss and P&L as alternative names for the income statement.", "difficulty": "Easy"},
    {"chapter": "What the Income Statement Is", "chapter_num": 1, "question": "Unlike the balance sheet, the income statement covers -", "a": "a single moment in time", "b": "a period, e.g. 1 January 2025 to 31 December 2025", "c": "a rolling five-year average", "d": "the date of the AGM only", "answer": "b", "explanation": "The income statement covers a PERIOD, whereas the balance sheet is a snapshot at a single MOMENT.", "difficulty": "Easy"},
    {"chapter": "What the Income Statement Is", "chapter_num": 1, "question": "In one line, MTN Ghana's FY2025 income statement showed -", "a": "Revenue GHS 24.43BN -> Profit after tax GHS 7.84BN", "b": "Assets GHS 62.39BN = Liabilities + Equity", "c": "Operating cash of GHS 7.6BN", "d": "A cash increase of GHS 1.01BN", "answer": "a", "explanation": "MTN's FY2025 income statement in one line: Revenue GHS 24.43BN through to Profit after tax GHS 7.84BN.", "difficulty": "Easy"},
    {"chapter": "What the Income Statement Is", "chapter_num": 1, "question": "Which question does the income statement primarily answer?", "a": "What does the company own and owe?", "b": "Did the company make a profit, and where did every cedi of revenue go?", "c": "Does the company have the actual cash?", "d": "How much money is held in trust for customers?", "answer": "b", "explanation": "The income statement answers whether MTN made a profit and traces where every cedi of revenue went.", "difficulty": "Easy"},
    {"chapter": "What the Income Statement Is", "chapter_num": 1, "question": "The masterclass describes the shape of the income statement using which analogy?", "a": "A ladder", "b": "A funnel -- one number enters at the top, costs are subtracted in layers, profit drips out the bottom", "c": "A balance scale", "d": "A closed loop with no start or end", "answer": "b", "explanation": "Revenue enters at the top as one number; costs are subtracted in layers; what survives at the bottom is profit -- the funnel analogy.", "difficulty": "Easy"},

    # Chapter 2: Revenue Recognition & Composition
    {"chapter": "Revenue Recognition & Composition", "chapter_num": 2, "question": "Under accrual accounting, MTN recognises revenue when -", "a": "cash is received from the customer", "b": "the service is delivered to the customer, regardless of when cash arrives", "c": "the invoice is issued", "d": "the financial year ends", "answer": "b", "explanation": "Revenue is recognised when the service is DELIVERED, not when it is PAID for.", "difficulty": "Medium"},
    {"chapter": "Revenue Recognition & Composition", "chapter_num": 2, "question": "A customer who used GHS 50 of data in December but pays in January -", "a": "counts as January revenue, since that is when cash arrived", "b": "counts as December revenue, since that is when the service was delivered", "c": "is not recorded as revenue at all", "d": "is recorded as a contract liability", "answer": "b", "explanation": "Revenue is recognised on delivery of the service, so it counts as December revenue even though cash arrives later.", "difficulty": "Medium"},
    {"chapter": "Revenue Recognition & Composition", "chapter_num": 2, "question": "Prepaid airtime bought in December but not yet used by year-end is treated as -", "a": "revenue in the month it was purchased", "b": "a liability (contract liability) until the customer actually uses it", "c": "an asset on the income statement", "d": "other income", "answer": "b", "explanation": "Cash received for services not yet delivered sits as a contract liability, not revenue, until the customer consumes it.", "difficulty": "Medium"},
    {"chapter": "Revenue Recognition & Composition", "chapter_num": 2, "question": "What was MTN Ghana's total revenue for FY2025?", "a": "GHS 17,948,326k", "b": "GHS 14,690,333k", "c": "GHS 24,430,308k", "d": "GHS 7,839,930k", "answer": "c", "explanation": "MTN's FY2025 total revenue was GHS 24,430,308k, up from GHS 17,948,326k in 2024.", "difficulty": "Easy"},
    {"chapter": "Revenue Recognition & Composition", "chapter_num": 2, "question": "Which revenue segment was MTN's single largest contributor in FY2025?", "a": "Digital & Fintech (MoMo, ayoba)", "b": "Network services (voice, data, SMS)", "c": "Devices & accessories", "d": "Interconnect & roaming", "answer": "b", "explanation": "Network services contributed GHS 17,004,316k, well above Digital & Fintech's GHS 6,699,403k.", "difficulty": "Medium"},
    {"chapter": "Revenue Recognition & Composition", "chapter_num": 2, "question": "Digital & Fintech revenue represented approximately what share of MTN's FY2025 total revenue?", "a": "11.6%", "b": "27.4%", "c": "36.1%", "d": "60.1%", "answer": "b", "explanation": "Digital & Fintech (GHS 6,699,403k) was about 27.4% of total revenue, up slightly from 27.1% in 2024.", "difficulty": "Medium"},
    {"chapter": "Revenue Recognition & Composition", "chapter_num": 2, "question": "MTN's FY2025 revenue grew by approximately what percentage over FY2024?", "a": "43.5%", "b": "55.9%", "c": "36.1%", "d": "59.4%", "answer": "c", "explanation": "Revenue grew from GHS 17,948,326k to GHS 24,430,308k, a rise of about 36.1%.", "difficulty": "Medium"},

    # Chapter 3: Other Income & Direct Costs
    {"chapter": "Other Income & Direct Costs", "chapter_num": 3, "question": "MTN's Group \"Other income\" of GHS 13.18 million in FY2025 mainly came from -", "a": "interest earned on bank deposits", "b": "prize money from MTN Group's 'Ambition 2025' challenge plus support for testing a gaming platform", "c": "sale of surplus towers", "d": "dividends received from subsidiaries", "answer": "b", "explanation": "The notes reveal the GHS 13.18m of other income as prize money and gaming-platform testing support -- not core telecom revenue.", "difficulty": "Medium"},
    {"chapter": "Other Income & Direct Costs", "chapter_num": 3, "question": "Why was the Company-only 'other income' figure (GHS 113.47M) far higher than the Group figure (GHS 13.18M)?", "a": "A misprint in the annual report", "b": "Scancom PLC charges its subsidiary MobileMoney Limited for admin support, which cancels out on consolidation", "c": "The Group figure excludes all foreign subsidiaries", "d": "Other income is only recognised at Group level", "answer": "b", "explanation": "Income to the parent from charging MMFL is a cost to the subsidiary; on consolidation the two amounts cancel out.", "difficulty": "Hard"},
    {"chapter": "Other Income & Direct Costs", "chapter_num": 3, "question": "MTN's direct network operating costs (transmission, network, leased lines, spectrum & regulatory fees) for FY2025 totalled -", "a": "GHS 570,792k", "b": "GHS 2,290,857k", "c": "GHS 78,606k", "d": "GHS 9,753,157k", "answer": "b", "explanation": "Direct network operating costs were GHS 2,290,857k, made up of transmission, network, leased lines and spectrum & regulatory fees.", "difficulty": "Medium"},
    {"chapter": "Other Income & Direct Costs", "chapter_num": 3, "question": "Interconnect and roaming COSTS fell 17.8% in FY2025 even as revenue grew 36.1%. What explains this?", "a": "MTN renegotiated much lower rates with Telecel and AT", "b": "Ghanaians increasingly use WhatsApp/data instead of cross-network calls, cutting both interconnect costs and interconnect revenue", "c": "A regulatory cap was imposed on interconnect fees", "d": "MTN discontinued international roaming", "answer": "b", "explanation": "Data is eating voice from both sides of the P&L -- MTN pays other networks less, but also earns less interconnect revenue (down 11.6%).", "difficulty": "Hard"},
    {"chapter": "Other Income & Direct Costs", "chapter_num": 3, "question": "Direct costs as a percentage of revenue improved from FY2024 to FY2025. What was the improvement?", "a": "12.0 percentage points", "b": "16.4 percentage points", "c": "4.4 percentage points", "d": "36.1 percentage points", "answer": "c", "explanation": "Direct costs fell from 16.4% of revenue in FY2024 to 12.0% in FY2025, an improvement of 4.4 percentage points.", "difficulty": "Medium"},
    {"chapter": "Other Income & Direct Costs", "chapter_num": 3, "question": "What did MTN pay for the handsets and accessories it resold in FY2025?", "a": "GHS 2,290,857k", "b": "GHS 570,792k", "c": "GHS 78,606k", "d": "GHS 1,061,001k", "answer": "c", "explanation": "Cost of devices and accessories was GHS 78,606k -- tiny, since MTN is not fundamentally a phone shop.", "difficulty": "Easy"},

    # Chapter 4: Operating Expenses
    {"chapter": "Operating Expenses", "chapter_num": 4, "question": "Which operating expense line was the single biggest cost in the whole company for FY2025?", "a": "Employee expenses", "b": "Selling, distribution and marketing", "c": "Other operating expenses", "d": "Depreciation", "answer": "b", "explanation": "Selling, distribution and marketing (GHS 3,411,149k) was the biggest cost in the company -- more than three times the wage bill.", "difficulty": "Medium"},
    {"chapter": "Operating Expenses", "chapter_num": 4, "question": "Employee expenses represented what share of MTN's FY2025 revenue?", "a": "14%", "b": "32.1%", "c": "4.3%", "d": "60.1%", "answer": "c", "explanation": "Employee expenses were only 4.3% of revenue, illustrating that telecoms are not labour-intensive businesses.", "difficulty": "Medium"},
    {"chapter": "Operating Expenses", "chapter_num": 4, "question": "Selling, distribution and marketing costs were roughly how many times MTN's entire wage bill in FY2025?", "a": "About half", "b": "Roughly equal", "c": "More than three times", "d": "Ten times", "answer": "c", "explanation": "GHS 3.41BN of selling & distribution cost was more than three times the GHS 1.06BN wage bill.", "difficulty": "Medium"},
    {"chapter": "Operating Expenses", "chapter_num": 4, "question": "Why does the masterclass argue MTN's high selling & distribution cost is structural, not waste?", "a": "It funds MTN Group's head office in South Africa", "b": "It is the cost of maintaining the MoMo agent network, which pays a commission on every transaction, so it must grow as MoMo grows", "c": "It is a one-off marketing campaign", "d": "It is mandated by NCA regulation", "answer": "b", "explanation": "Every agent takes a commission on every MoMo transaction, so as MoMo revenue grows at 37.6%, this cost structurally grows too.", "difficulty": "Hard"},
    {"chapter": "Operating Expenses", "chapter_num": 4, "question": "MTN's 'Other operating expenses' in FY2025 mainly comprised -", "a": "handset costs only", "b": "MTN Group management fees, professional fees, insurance and admin costs", "c": "interconnect payments to other networks", "d": "dividend payments to shareholders", "answer": "b", "explanation": "Other operating expenses covered Group management fees, professional fees, insurance and office/admin costs.", "difficulty": "Medium"},
    {"chapter": "Operating Expenses", "chapter_num": 4, "question": "MTN's total operating expenses (employee + selling & distribution + other operating) for FY2025 were -", "a": "GHS 2,940,255k", "b": "GHS 6,812,902k", "c": "GHS 9,753,157k", "d": "GHS 14,690,333k", "answer": "b", "explanation": "Employee (1,061,001) + Selling & distribution (3,411,149) + Other operating (2,340,752) = GHS 6,812,902k.", "difficulty": "Medium"},

    # Chapter 5: EBITDA
    {"chapter": "EBITDA", "chapter_num": 5, "question": "EBITDA stands for -", "a": "Earnings Before Interest, Tax, Depreciation and Amortisation", "b": "Earnings Before Income, Tax and Dividends Allocated", "c": "Earnings Before Interest, Tax and Debt Amortised", "d": "Estimated Business Income minus Total Debt and Assets", "answer": "a", "explanation": "EBITDA = Earnings Before Interest, Tax, Depreciation and Amortisation.", "difficulty": "Easy"},
    {"chapter": "EBITDA", "chapter_num": 5, "question": "What was MTN Ghana's EBITDA for FY2025?", "a": "GHS 11,960,724k", "b": "GHS 24,430,308k", "c": "GHS 14,690,333k", "d": "GHS 7,839,930k", "answer": "c", "explanation": "MTN's FY2025 EBITDA was GHS 14,690,333k, giving a 60.1% margin.", "difficulty": "Easy"},
    {"chapter": "EBITDA", "chapter_num": 5, "question": "MTN's FY2025 EBITDA margin was approximately -", "a": "32.1%", "b": "49.0%", "c": "60.1%", "d": "12.0%", "answer": "c", "explanation": "EBITDA margin of 60.1% means every GHS 100 of revenue leaves GHS 60.10 before D&A, interest and tax.", "difficulty": "Medium"},
    {"chapter": "EBITDA", "chapter_num": 5, "question": "Why is EBITDA useful for comparing two telecom companies in different countries?", "a": "It strips out differences in financing and tax positions, isolating operating performance", "b": "It already includes tax and depreciation", "c": "It always equals net profit", "d": "IFRS requires it to be identical across all companies", "answer": "a", "explanation": "EBITDA lets you compare operating performance without differing debt levels or tax positions getting in the way.", "difficulty": "Medium"},
    {"chapter": "EBITDA", "chapter_num": 5, "question": "What is the key limitation of EBITDA that the masterclass emphasises?", "a": "It overstates revenue figures", "b": "It is not cash and it is not profit -- it ignores the real cost of replacing and expanding assets like towers", "c": "It is only relevant to banks", "d": "It cannot be calculated for telecom companies", "answer": "b", "explanation": "EBITDA deliberately ignores that MTN must spend billions a year replacing and expanding towers -- great EBITDA does not guarantee a good investment.", "difficulty": "Medium"},
    {"chapter": "EBITDA", "chapter_num": 5, "question": "MTN management guided that its ~60.1% EBITDA margin might not repeat, since their own stated guidance range is -", "a": "\"mid-to-upper fifties\"", "b": "\"above 70%\"", "c": "\"below 40%\"", "d": "\"exactly 60%\"", "answer": "a", "explanation": "Management's own guidance of 'mid-to-upper fifties' signals that 60.1% may have been an unusually strong year.", "difficulty": "Hard"},

    # Chapter 6: Depreciation, Amortisation & EBIT
    {"chapter": "Depreciation, Amortisation & EBIT", "chapter_num": 6, "question": "In the tower example, why does accounting spread a GHS 100 million tower's cost over 10 years instead of expensing it all at once?", "a": "Tax law strictly requires it", "b": "Otherwise the purchase year would show a huge loss and the following nine years would look artificially wonderful", "c": "The tower has no resale value", "d": "It is done to reduce reported revenue", "answer": "b", "explanation": "Spreading the cost over the years the tower earns revenue avoids a distorted, artificial picture of profitability.", "difficulty": "Medium"},
    {"chapter": "Depreciation, Amortisation & EBIT", "chapter_num": 6, "question": "What is amortisation, as distinguished from depreciation, in the masterclass?", "a": "The same idea as depreciation, applied to intangible items like spectrum licences and software", "b": "A cash outflow for loan repayments", "c": "A one-off tax charge", "d": "The same as an impairment of trade receivables", "answer": "a", "explanation": "Amortisation applies the depreciation concept to things you cannot touch -- spectrum licences and software.", "difficulty": "Medium"},
    {"chapter": "Depreciation, Amortisation & EBIT", "chapter_num": 6, "question": "What was MTN's total Depreciation & Amortisation (D&A) charge for FY2025?", "a": "GHS 2,322,138k", "b": "GHS 407,471k", "c": "GHS 2,729,609k", "d": "GHS 6,414,306k", "answer": "c", "explanation": "Depreciation (2,322,138) + Amortisation (407,471) = total D&A of GHS 2,729,609k.", "difficulty": "Medium"},
    {"chapter": "Depreciation, Amortisation & EBIT", "chapter_num": 6, "question": "The masterclass's key sentence to memorise about depreciation is -", "a": "\"Depreciation is a payment, but it is not a cost\"", "b": "\"Depreciation is a cost, but it is not a payment\"", "c": "\"Depreciation always equals capex\"", "d": "\"Depreciation reduces cash directly\"", "answer": "b", "explanation": "MTN's bank balance did not fall because of depreciation -- not one cedi left the building this year for that charge.", "difficulty": "Medium"},
    {"chapter": "Depreciation, Amortisation & EBIT", "chapter_num": 6, "question": "Operating Profit (EBIT) is calculated as -", "a": "EBITDA plus finance income", "b": "EBITDA minus Depreciation and Amortisation", "c": "Revenue minus all costs including tax", "d": "Profit after tax plus dividends", "answer": "b", "explanation": "EBIT = EBITDA less D&A -- it accepts that the network genuinely wears out as a real economic cost.", "difficulty": "Medium"},
    {"chapter": "Depreciation, Amortisation & EBIT", "chapter_num": 6, "question": "MTN's FY2025 EBIT margin was 49.0% versus an EBITDA margin of 60.1%. What does the 11.1 percentage point gap represent?", "a": "Tax paid to government", "b": "The cost of the network wearing out (D&A)", "c": "Dividends paid to shareholders", "d": "Net finance costs", "answer": "b", "explanation": "The gap between EBITDA and EBIT margins is exactly the cost of D&A as a share of revenue.", "difficulty": "Medium"},
    {"chapter": "Depreciation, Amortisation & EBIT", "chapter_num": 6, "question": "Why do analysts still quote EBITDA even though EBIT is described as the 'more honest' figure?", "a": "EBITDA is mandated by the SEC for all disclosures", "b": "Depreciation involves accounting judgement (useful life, method) that can differ between identical companies, and EBITDA strips that judgement out", "c": "EBIT cannot be calculated reliably", "d": "EBITDA is always the higher number, so it looks more impressive", "answer": "b", "explanation": "Two identical companies can report different EBIT purely from depreciation judgement; EBITDA removes that variable for comparison.", "difficulty": "Hard"},

    # Chapter 7: Finance Income/Costs & Tax
    {"chapter": "Finance Income/Costs & Tax", "chapter_num": 7, "question": "MTN earned finance income in FY2025 mainly from -", "a": "selling surplus towers", "b": "interest on its cash held in call and fixed deposits", "c": "trading foreign currency derivatives", "d": "rental income from towers", "answer": "b", "explanation": "Finance income of GHS 450,066k was interest earned on MTN's large cash balances at Ghanaian interest rates.", "difficulty": "Medium"},
    {"chapter": "Finance Income/Costs & Tax", "chapter_num": 7, "question": "MTN's net finance cost for FY2025 was -", "a": "GHS 450,066k", "b": "GHS 1,098,785k", "c": "GHS 648,719k", "d": "GHS 3,472,075k", "answer": "c", "explanation": "Finance income (450,066) less finance costs (1,098,785) gives a net finance cost of GHS 648,719k.", "difficulty": "Medium"},
    {"chapter": "Finance Income/Costs & Tax", "chapter_num": 7, "question": "Why does a company with zero bank borrowings still report substantial finance costs?", "a": "It is simply a reporting error", "b": "IFRS 16 treats leased assets (like tower sites) as if bought with borrowed money, creating artificial 'interest' charges, plus FX losses on dollar-priced equipment", "c": "Finance costs are charged regardless of any circumstances", "d": "Finance costs relate only to dividend payments", "answer": "b", "explanation": "MTN has zero bank debt, but leases thousands of sites; IFRS 16 plus FX losses explain the GHS 1.10BN of finance costs.", "difficulty": "Hard"},
    {"chapter": "Finance Income/Costs & Tax", "chapter_num": 7, "question": "The Growth and Sustainability Levy (GSL) charged to MTN in FY2025 was calculated as -", "a": "25% of profit before tax", "b": "5% of profit before tax", "c": "5% of revenue", "d": "A fixed amount regardless of profit", "answer": "b", "explanation": "The GSL was GHS 565,600k, equal to 5% of profit before tax (GHS 11,312,005k).", "difficulty": "Medium"},
    {"chapter": "Finance Income/Costs & Tax", "chapter_num": 7, "question": "What was MTN's effective tax-and-levy rate on profit before tax in FY2025?", "a": "25.0%", "b": "30.7%", "c": "47.1%", "d": "60.1%", "answer": "b", "explanation": "Total taxes and levies of GHS 3,472,075k against PBT of GHS 11,312,005k gives an effective rate of 30.7%.", "difficulty": "Medium"},
    {"chapter": "Finance Income/Costs & Tax", "chapter_num": 7, "question": "The Growth and Sustainability Levy is best described as -", "a": "standard corporate income tax", "b": "a separate Ghanaian levy, introduced in 2023, applying to sectors like banks, telecoms and mining -- distinct from corporate tax", "c": "a withholding tax on dividends", "d": "a tax applying only to foreign shareholders", "answer": "b", "explanation": "The GSL is a distinct levy from corporate income tax, introduced in 2023 and applied across specific sectors.", "difficulty": "Medium"},
    {"chapter": "Finance Income/Costs & Tax", "chapter_num": 7, "question": "MTN's profit before tax for FY2025 was -", "a": "GHS 11,960,724k", "b": "GHS 11,312,005k", "c": "GHS 14,690,333k", "d": "GHS 7,839,930k", "answer": "b", "explanation": "Operating profit (11,960,724) less net finance costs (648,719) gives profit before tax of GHS 11,312,005k.", "difficulty": "Medium"},

    # Chapter 8: Profit After Tax, EPS & Ratios
    {"chapter": "Profit After Tax, EPS & Ratios", "chapter_num": 8, "question": "MTN's profit after tax (PAT) for FY2025 was -", "a": "GHS 11,312,005k", "b": "GHS 14,690,333k", "c": "GHS 7,839,930k", "d": "GHS 24,430,308k", "answer": "c", "explanation": "After levy and income tax of GHS 3,472,075k, MTN's PAT for FY2025 was GHS 7,839,930k.", "difficulty": "Easy"},
    {"chapter": "Profit After Tax, EPS & Ratios", "chapter_num": 8, "question": "Profit after tax can only go to one of two destinations. What are they?", "a": "Tax and dividends", "b": "Dividends, or retained earnings kept inside the company", "c": "Capex or debt repayment", "d": "Revenue or cost of sales", "answer": "b", "explanation": "There is no third option -- PAT is either paid out as dividends or retained inside the business.", "difficulty": "Easy"},
    {"chapter": "Profit After Tax, EPS & Ratios", "chapter_num": 8, "question": "MTN's EPS for FY2025 (GHS 7,839,930k divided by shares in issue) was calculated using approximately how many shares?", "a": "13.24 billion", "b": "24.43 billion", "c": "7.84 billion", "d": "62.39 billion", "answer": "a", "explanation": "GHS 7,839,930k / 13.24BN shares = GHS 0.592 EPS.", "difficulty": "Medium"},
    {"chapter": "Profit After Tax, EPS & Ratios", "chapter_num": 8, "question": "With EPS of GHS 0.592 and a share price of GHS 6.44 (July 2026), MTN's P/E ratio was approximately -", "a": "6.0x", "b": "10.9x", "c": "32.1x", "d": "60.1x", "answer": "b", "explanation": "P/E = Price / EPS = 6.44 / 0.592 ≈ 10.9x on 2025 earnings.", "difficulty": "Medium"},
    {"chapter": "Profit After Tax, EPS & Ratios", "chapter_num": 8, "question": "MTN's PAT grew by approximately what percentage from FY2024 to FY2025?", "a": "36.1%", "b": "43.5%", "c": "55.9%", "d": "59.4%", "answer": "c", "explanation": "PAT grew from GHS 5,029,065k (2024) to GHS 7,839,930k (2025), an increase of about 55.9%.", "difficulty": "Medium"},
    {"chapter": "Profit After Tax, EPS & Ratios", "chapter_num": 8, "question": "What is the analyst's warning at the end of Part 1, before moving into the cash flow statement?", "a": "The profit figure is definitely fraudulent", "b": "You have not yet seen whether the GHS 7.84BN profit is backed by actual cash -- that is the whole point of Part 2", "c": "EPS was calculated incorrectly", "d": "No dividends were actually paid", "answer": "b", "explanation": "The masterclass insists profit alone tells only half the story until it is checked against real cash generation.", "difficulty": "Medium"},
]

CASH_FLOW_QUESTIONS = [
    # Chapter 1: Purpose & Method of the Cash Flow Statement
    {"chapter": "Purpose & Method of the Cash Flow Statement", "chapter_num": 1, "question": "Analysts read the cash flow statement first because -", "a": "it is the shortest of the three statements", "b": "profit depends on judgement, but cash in the bank is not a matter of judgement", "c": "it is legally required to appear first in the annual report", "d": "it requires no adjustments at all", "answer": "b", "explanation": "Either the money is in the account on 31 December or it is not -- there is no judgement available, unlike with profit.", "difficulty": "Medium"},
    {"chapter": "Purpose & Method of the Cash Flow Statement", "chapter_num": 1, "question": "Which of the following is NOT one of the three sections of MTN's cash flow statement?", "a": "Operating activities", "b": "Investing activities", "c": "Financing activities", "d": "Retained activities", "answer": "d", "explanation": "The three sections are Operating, Investing and Financing activities -- there is no 'Retained activities' section.", "difficulty": "Easy"},
    {"chapter": "Purpose & Method of the Cash Flow Statement", "chapter_num": 1, "question": "MTN's FY2025 cash flow statement, in one line, shows profit of GHS 7.84BN converting into operating cash of -", "a": "GHS 4.30BN", "b": "GHS 7.6BN", "c": "GHS 14.69BN", "d": "GHS 6.41BN", "answer": "b", "explanation": "Profit of GHS 7.84BN converted into operating cash of GHS 7.6BN, and the bank balance rose GHS 1.01BN.", "difficulty": "Easy"},
    {"chapter": "Purpose & Method of the Cash Flow Statement", "chapter_num": 1, "question": "Which method of preparing the cash flow statement does MTN use, like almost every listed company?", "a": "The direct method, listing every cash receipt and payment", "b": "The indirect method, starting from profit and adjusting for non-cash and non-operating items", "c": "A hybrid method unique to Ghana", "d": "No formal method -- a management estimate", "answer": "b", "explanation": "The indirect method starts from profit before tax and reverses out non-cash items -- harder to read, but it comes straight from the ledgers.", "difficulty": "Medium"},
    {"chapter": "Purpose & Method of the Cash Flow Statement", "chapter_num": 1, "question": "When you see 'Profit before tax' at the top of a cash flow statement, what does it mean?", "a": "Profit before tax is itself being treated as cash", "b": "It is the starting point, and every line below it is a correction converting it toward actual cash", "c": "It is an error and should be ignored", "d": "It is the closing cash balance", "answer": "b", "explanation": "The statement starts from profit and corrects it, line by line, until it becomes cash.", "difficulty": "Medium"},
    {"chapter": "Purpose & Method of the Cash Flow Statement", "chapter_num": 1, "question": "Does the existence of the cash flow statement mean the income statement is dishonest?", "a": "Yes, the income statement is unreliable and should be discarded", "b": "No -- a business that only measured cash would look terrible in any investment year and wonderful when it stopped investing, which would be nonsense", "c": "Yes, only cash matters to shareholders", "d": "The income statement exists only for tax purposes", "answer": "b", "explanation": "The correct posture is to read cash flow first to check you can believe the income statement, then read the income statement to understand the business.", "difficulty": "Medium"},

    # Chapter 2: Operating Activities -- Reversing Non-Cash Items
    {"chapter": "Operating Activities: Reversing Non-Cash Items", "chapter_num": 2, "question": "The operating section of the cash flow statement starts by adding back which non-cash items to profit before tax?", "a": "Revenue and cost of sales", "b": "Depreciation, amortisation and net finance costs", "c": "Dividends and share capital", "d": "Capex and borrowings", "answer": "b", "explanation": "Depreciation, amortisation and net finance costs are added back because they affected profit but not cash.", "difficulty": "Medium"},
    {"chapter": "Operating Activities: Reversing Non-Cash Items", "chapter_num": 2, "question": "MTN's profit before tax of GHS 11,312,005k, after adding back D&A and net finance costs, produces a subtotal that equals -", "a": "EBIT", "b": "EBITDA", "c": "PAT", "d": "Net operating cash", "answer": "b", "explanation": "The subtotal of GHS 14,690,333k equals EBITDA exactly -- not a coincidence.", "difficulty": "Medium"},
    {"chapter": "Operating Activities: Reversing Non-Cash Items", "chapter_num": 2, "question": "Why does the subtotal (profit before tax + D&A + net finance costs) land exactly on EBITDA?", "a": "It is a coincidence unique to MTN", "b": "EBITDA is defined as earnings before exactly those items (interest, tax, D&A), so adding them back rebuilds EBITDA from the bottom up", "c": "Auditors force this equality by convention", "d": "EBITDA and the subtotal use different accounting standards", "answer": "b", "explanation": "Since EBITDA is earnings before interest, tax, D&A, adding those exact items back to profit before tax reconstructs EBITDA.", "difficulty": "Hard"},
    {"chapter": "Operating Activities: Reversing Non-Cash Items", "chapter_num": 2, "question": "Net finance costs are added back at this early stage of the cash flow statement because -", "a": "they never affect cash at all", "b": "actual interest paid is deducted separately, further down the statement, avoiding double-counting", "c": "they are not considered real costs", "d": "MTN has no finance costs", "answer": "b", "explanation": "Finance costs are removed here and then the actual cash interest paid is deducted lower down the cash flow statement.", "difficulty": "Hard"},
    {"chapter": "Operating Activities: Reversing Non-Cash Items", "chapter_num": 2, "question": "What amount was added back for depreciation in MTN's FY2025 cash flow statement?", "a": "GHS 407,471k", "b": "GHS 2,322,138k", "c": "GHS 648,719k", "d": "GHS 2,729,609k", "answer": "b", "explanation": "Depreciation of GHS 2,322,138k was added back since no cash left the building this year for that charge.", "difficulty": "Medium"},
    {"chapter": "Operating Activities: Reversing Non-Cash Items", "chapter_num": 2, "question": "What amount was added back for amortisation in MTN's FY2025 cash flow statement?", "a": "GHS 2,322,138k", "b": "GHS 407,471k", "c": "GHS 780,600k", "d": "GHS 44,122k", "answer": "b", "explanation": "Amortisation of GHS 407,471k, covering licences and software, was added back for the same reasoning as depreciation.", "difficulty": "Medium"},
    {"chapter": "Operating Activities: Reversing Non-Cash Items", "chapter_num": 2, "question": "Why is EBITDA sometimes called a 'proxy for operating cash flow'?", "a": "It is exactly equal to the closing cash balance", "b": "It is where cash generation starts in the indirect-method reconciliation, though not where it ends", "c": "It already includes capital expenditure", "d": "It is calculated using the direct method", "answer": "b", "explanation": "EBITDA is the subtotal cash generation starts from -- working capital, tax paid and interest are still to come.", "difficulty": "Medium"},

    # Chapter 3: Operating Activities -- Working Capital
    {"chapter": "Operating Activities: Working Capital", "chapter_num": 3, "question": "If MTN's trade receivables RISE during the year, what happens on the cash flow statement?", "a": "The increase is added to cash", "b": "The increase is deducted from cash, because revenue was booked but not yet collected", "c": "It has no cash flow effect", "d": "It increases EBITDA", "answer": "b", "explanation": "A rise in receivables means revenue was recognised without cash arriving, so it is deducted in the working capital adjustment.", "difficulty": "Medium"},
    {"chapter": "Operating Activities: Working Capital", "chapter_num": 3, "question": "If MTN's trade payables RISE during the year, what happens on the cash flow statement?", "a": "The increase is added to cash, because the cost hit profit but cash stayed in the bank", "b": "The increase is deducted from cash", "c": "It reduces revenue", "d": "It has no cash flow effect", "answer": "a", "explanation": "A rise in payables means a cost was recognised but not yet paid, so cash is added back in the working capital adjustment.", "difficulty": "Medium"},
    {"chapter": "Operating Activities: Working Capital", "chapter_num": 3, "question": "A rise in contract liabilities (unused prepaid airtime) means -", "a": "cash came in before revenue was recognised, so it is added to cash flow", "b": "revenue was recognised with no cash received", "c": "it is deducted from cash flow", "d": "it appears only on the income statement", "answer": "a", "explanation": "Customers paid for airtime not yet consumed -- cash arrived with no matching revenue yet, so the increase adds to cash flow.", "difficulty": "Medium"},
    {"chapter": "Operating Activities: Working Capital", "chapter_num": 3, "question": "In the worked example, MTN books GHS 1,000 of December revenue that a client pays in February. What happens at 31 December?", "a": "GHS 1,000 is in the bank and nothing is in receivables", "b": "GHS 1,000 sits in trade receivables and GHS 0 is in the bank; cash flow shows 'increase in receivables (1,000)', reversing the profit", "c": "The revenue is cancelled entirely", "d": "It is treated as a contract liability", "answer": "b", "explanation": "Profit rose GHS 1,000 on the income statement, but since no cash arrived, the GHS 1,000 is reversed out on the cash flow statement.", "difficulty": "Hard"},
    {"chapter": "Operating Activities: Working Capital", "chapter_num": 3, "question": "MTN's provision for impairment of trade receivables in FY2025 -", "a": "fell from GHS 253,871k to GHS 120,640k", "b": "more than doubled, from GHS 120,640k to GHS 253,871k", "c": "stayed flat year on year", "d": "was eliminated entirely", "answer": "b", "explanation": "The impairment provision more than doubled, signalling growing expectation that some customers will not pay.", "difficulty": "Medium"},
    {"chapter": "Operating Activities: Working Capital", "chapter_num": 3, "question": "Why does the masterclass argue telecoms like MTN rarely die of cash starvation, unlike most growing businesses?", "a": "They have no operating costs", "b": "Customers pay for prepaid airtime BEFORE they consume it, so growth funds the business rather than starving it of cash", "c": "They receive government subsidies", "d": "They have unlimited access to borrowing", "answer": "b", "explanation": "Contract liabilities are effectively an interest-free loan from customers -- growth funds MTN rather than draining it.", "difficulty": "Hard"},
    {"chapter": "Operating Activities: Working Capital", "chapter_num": 3, "question": "MTN's contract liabilities (unused prepaid airtime) rose during FY2025 from GHS 251,040k to -", "a": "GHS 448,919k", "b": "GHS 780,600k", "c": "GHS 1,170,834k", "d": "GHS 44,122k", "answer": "a", "explanation": "Contract liabilities rose to GHS 448,919k, reflecting customers pre-funding MTN with unused prepaid airtime.", "difficulty": "Medium"},

    # Chapter 4: Operating Activities -- Tax Paid & Net Operating Cash
    {"chapter": "Operating Activities: Tax Paid & Net Operating Cash", "chapter_num": 4, "question": "MTN's income tax CHARGE on the income statement (GHS 2,906,475k) differed from the tax PAID in cash (GHS 3,394,101k) by -", "a": "GHS 780,600k", "b": "GHS 487,626k", "c": "GHS 253,871k", "d": "GHS 1,170,834k", "answer": "b", "explanation": "MTN paid the GRA GHS 487,626k more cash than the tax charge on the income statement.", "difficulty": "Medium"},
    {"chapter": "Operating Activities: Tax Paid & Net Operating Cash", "chapter_num": 4, "question": "Which of these is NOT given as a reason the tax charge and tax paid can differ?", "a": "Timing -- taxes on prior-year profits settled in the current year", "b": "Deferred tax amounts payable only in future years", "c": "Prior-year GRA assessments settled in whichever year they are agreed", "d": "MTN chooses not to pay tax it disagrees with", "answer": "d", "explanation": "The masterclass cites timing, deferred tax and prior-year assessments -- not a choice by MTN to withhold payment.", "difficulty": "Medium"},
    {"chapter": "Operating Activities: Tax Paid & Net Operating Cash", "chapter_num": 4, "question": "MTN's current tax asset on the balance sheet grew from GHS 386,320k in 2024 to how much in 2025?", "a": "GHS 1,170,834k", "b": "GHS 3,394,101k", "c": "GHS 2,906,475k", "d": "GHS 565,600k", "answer": "a", "explanation": "The current tax asset ballooned to GHS 1,170,834k -- MTN has effectively overpaid and carries a credit with the GRA.", "difficulty": "Medium"},
    {"chapter": "Operating Activities: Tax Paid & Net Operating Cash", "chapter_num": 4, "question": "What is described as the 'single largest unquantified risk' in MTN's accounts?", "a": "Currency risk on dollar-denominated equipment", "b": "GRA audits of tax years 2014 to 2022 with 'no reliable estimate' of exposure", "c": "Customer churn in the prepaid segment", "d": "Spectrum licence renewal costs", "answer": "b", "explanation": "The open GRA audits for 2014-2022, combined with a growing tax asset, are flagged as the largest unquantified risk.", "difficulty": "Hard"},
    {"chapter": "Operating Activities: Tax Paid & Net Operating Cash", "chapter_num": 4, "question": "MTN's net cash from operating activities for FY2025 was approximately -", "a": "GHS 4,768,000k", "b": "GHS 6,414,306k", "c": "GHS 7,600,000k", "d": "GHS 14,690,333k", "answer": "c", "explanation": "Net cash from operating activities was approximately GHS 7.6 billion, up 59.4% on 2024.", "difficulty": "Easy"},
    {"chapter": "Operating Activities: Tax Paid & Net Operating Cash", "chapter_num": 4, "question": "Net cash from operating activities grew by what percentage from FY2024 to FY2025?", "a": "36.1%", "b": "43.5%", "c": "52%", "d": "59.4%", "answer": "d", "explanation": "MTN's own CFO describes operating cash rising 59.4% to GHS 7.6 billion.", "difficulty": "Medium"},
    {"chapter": "Operating Activities: Tax Paid & Net Operating Cash", "chapter_num": 4, "question": "MTN's cash conversion ratio (operating cash flow divided by EBITDA) for FY2025 was approximately -", "a": "12.3%", "b": "52%", "c": "55.3%", "d": "60.1%", "answer": "b", "explanation": "Cash conversion = 7.6 / 14.69 ≈ 52% -- roughly half of the accounting 'earnings engine' becomes spendable money.", "difficulty": "Medium"},

    # Chapter 5: Investing Activities
    {"chapter": "Investing Activities", "chapter_num": 5, "question": "MTN's total IFRS 16 capital expenditure for FY2025 was -", "a": "GHS 4,600,000k", "b": "GHS 780,600k", "c": "GHS 6,414,306k", "d": "GHS 1,000,000k", "answer": "c", "explanation": "Total IFRS 16 capex, including ex-lease capex, spectrum licences and right-of-use additions, was GHS 6,414,306k.", "difficulty": "Medium"},
    {"chapter": "Investing Activities", "chapter_num": 5, "question": "MTN's ex-lease capital expenditure (base stations, core network, IT systems, transmission) for FY2025 was -", "a": "GHS 6,414,306k", "b": "GHS 4,600,000k", "c": "GHS 780,600k", "d": "GHS 1,000,000k", "answer": "b", "explanation": "Ex-lease capex -- the real network build -- was GHS 4,600,000k, up 46.7% year on year.", "difficulty": "Medium"},
    {"chapter": "Investing Activities", "chapter_num": 5, "question": "MTN's spectrum licence purchases in FY2025 (rights to use radio frequencies from the NCA) totalled -", "a": "GHS 780,600k", "b": "GHS 1,000,000k", "c": "GHS 4,600,000k", "d": "GHS 6,414,306k", "answer": "a", "explanation": "MTN spent GHS 780,600k on new spectrum licences -- a right, not a physical machine.", "difficulty": "Medium"},
    {"chapter": "Investing Activities", "chapter_num": 5, "question": "Total IFRS 16 capex grew by what percentage in FY2025 versus 2024 (restated)?", "a": "46.7%", "b": "39.2%", "c": "26.3%", "d": "18.8%", "answer": "b", "explanation": "Total IFRS 16 capex rose from GHS 4,607,690k (2024 restated) to GHS 6,414,306k (2025), a rise of about 39.2%.", "difficulty": "Medium"},
    {"chapter": "Investing Activities", "chapter_num": 5, "question": "Which capex category grew as a share of the mix, from 13% (2024) to 28% (2025), reflecting a push into peri-urban and rural coverage?", "a": "IT Systems", "b": "Core Network", "c": "Radio & Infrastructure", "d": "Transmissions", "answer": "c", "explanation": "Radio & Infrastructure's share rose sharply as MTN pushed 4G coverage deeper into peri-urban and rural Ghana.", "difficulty": "Hard"},
    {"chapter": "Investing Activities", "chapter_num": 5, "question": "MTN's capex intensity (ex-lease capex divided by revenue) for FY2025 was approximately -", "a": "21.1%", "b": "17.4%", "c": "18.8%", "d": "26.3%", "answer": "c", "explanation": "Capex intensity rose slightly to 18.8% in FY2025 from 17.4% in FY2024.", "difficulty": "Medium"},
    {"chapter": "Investing Activities", "chapter_num": 5, "question": "MTN's guidance for capex in FY2026 was approximately -", "a": "GHS 4.8BN", "b": "GHS 6.4BN", "c": "GHS 780.6M", "d": "GHS 1.0BN", "answer": "a", "explanation": "MTN guided FY2026 capex of approximately GHS 4.8 billion.", "difficulty": "Medium"},

    # Chapter 6: Financing Activities
    {"chapter": "Financing Activities", "chapter_num": 6, "question": "The financing section of a mature, cash-generative company like MTN is typically -", "a": "inbound -- raising equity and drawing loans", "b": "outbound -- returning cash to owners and retiring debt", "c": "always exactly zero", "d": "identical to the investing section", "answer": "b", "explanation": "A young company's financing section is inbound; a mature company's, like MTN's, is outbound.", "difficulty": "Medium"},
    {"chapter": "Financing Activities", "chapter_num": 6, "question": "MTN's dividends paid to shareholders in FY2025 were -", "a": "GHS 3,311,455k", "b": "GHS 7,839,930k", "c": "GHS 4,528,475k", "d": "GHS 6,414,306k", "answer": "c", "explanation": "Dividends paid were GHS 4,528,475k, by far the largest financing outflow.", "difficulty": "Medium"},
    {"chapter": "Financing Activities", "chapter_num": 6, "question": "MTN's dividends are paid net of what withholding tax rate?", "a": "5%", "b": "8%", "c": "25%", "d": "30.7%", "answer": "b", "explanation": "Dividends are paid net of an 8% withholding tax.", "difficulty": "Medium"},
    {"chapter": "Financing Activities", "chapter_num": 6, "question": "MTN's total borrowings moved from GHS 70,443k at end-2024 to what amount at end-2025?", "a": "GHS 780,600k", "b": "GHS 4,298,477k", "c": "Zero -- completely debt-free", "d": "GHS 9,826,654k", "answer": "c", "explanation": "MTN repaid its last borrowings during 2025 and ended the year with zero bank debt.", "difficulty": "Medium"},
    {"chapter": "Financing Activities", "chapter_num": 6, "question": "Within the cash flow statement, the interest portion of IFRS 16 lease payments is recorded where?", "a": "In financing activities, alongside the capital repayment", "b": "In operating activities, while the capital (principal) portion sits in financing activities", "c": "In investing activities", "d": "It is not recorded anywhere", "answer": "b", "explanation": "The interest portion of lease payments sits in operating activities; the capital portion sits in financing activities.", "difficulty": "Hard"},
    {"chapter": "Financing Activities", "chapter_num": 6, "question": "In FY2025, MTN simultaneously did which three things, all funded from money it generated itself?", "a": "Raised new equity, took a bank loan, and paid dividends", "b": "Funded GHS 6.41BN of capex, paid GHS 4.53BN of dividends, and repaid its last borrowings to zero", "c": "Sold towers, cut dividends, and increased debt", "d": "Issued bonds, bought back shares, and expanded overseas", "answer": "b", "explanation": "MTN funded major capex, paid substantial dividends and cleared its remaining borrowings entirely from self-generated cash.", "difficulty": "Medium"},

    # Chapter 7: Cash Reconciliation & Free Cash Flow
    {"chapter": "Cash Reconciliation & Free Cash Flow", "chapter_num": 7, "question": "MTN's cash and cash equivalents at 1 January 2025 were -", "a": "GHS 4,298,477k", "b": "GHS 3,284,768k", "c": "GHS 7,600,000k", "d": "GHS 1,013,709k", "answer": "b", "explanation": "MTN opened FY2025 with GHS 3,284,768k of cash and cash equivalents.", "difficulty": "Medium"},
    {"chapter": "Cash Reconciliation & Free Cash Flow", "chapter_num": 7, "question": "MTN's cash and cash equivalents at 31 December 2025 were -", "a": "GHS 3,284,768k", "b": "GHS 4,298,477k", "c": "GHS 6,414,306k", "d": "GHS 14,690,333k", "answer": "b", "explanation": "MTN closed FY2025 with GHS 4,298,477k of cash -- identical to the balance sheet's cash line.", "difficulty": "Medium"},
    {"chapter": "Cash Reconciliation & Free Cash Flow", "chapter_num": 7, "question": "MTN's net increase in cash during FY2025 was -", "a": "GHS 1,013,709k", "b": "GHS 7,600,000k", "c": "GHS 6,414,306k", "d": "GHS 4,528,475k", "answer": "a", "explanation": "Cash rose GHS 1,013,709k over the year, from GHS 3,284,768k to GHS 4,298,477k.", "difficulty": "Medium"},
    {"chapter": "Cash Reconciliation & Free Cash Flow", "chapter_num": 7, "question": "What does the masterclass conclude a business that can invest heavily, pay dividends generously, deleverage AND still accumulate cash is doing?", "a": "Hiding losses through creative accounting", "b": "Generating more money than it needs", "c": "About to go bankrupt", "d": "Breaking accounting rules", "answer": "b", "explanation": "A business able to do all four at once is generating more cash than it currently needs to deploy.", "difficulty": "Medium"},
    {"chapter": "Cash Reconciliation & Free Cash Flow", "chapter_num": 7, "question": "MTN's Free Cash Flow (ex-lease), calculated as operating cash less ex-lease capex, was approximately -", "a": "GHS 7,600,000k", "b": "GHS 3,000,000k", "c": "GHS 4,600,000k", "d": "GHS 1,013,709k", "answer": "b", "explanation": "FCF (ex-lease) = 7,600,000 - 4,600,000 = GHS 3,000,000k.", "difficulty": "Medium"},
    {"chapter": "Cash Reconciliation & Free Cash Flow", "chapter_num": 7, "question": "MTN's FCF margin (FCF divided by revenue) for FY2025 was approximately -", "a": "12.3%", "b": "52%", "c": "60.1%", "d": "32.1%", "answer": "a", "explanation": "FCF margin = 3,000,000 / 24,430,308 ≈ 12.3%.", "difficulty": "Medium"},

    # Chapter 8: Cash Flow Ratios & Glossary
    {"chapter": "Cash Flow Ratios & Glossary", "chapter_num": 8, "question": "MTN's cash dividend cover (operating cash flow divided by dividends paid) for FY2025 was approximately -", "a": "0.5x", "b": "1.68x", "c": "2.35x", "d": "6.0x", "answer": "b", "explanation": "Cash dividend cover = 7,600,000 / 4,528,475 ≈ 1.68x -- operations comfortably fund the dividend.", "difficulty": "Medium"},
    {"chapter": "Cash Flow Ratios & Glossary", "chapter_num": 8, "question": "What does a cash dividend cover ratio below 1x signal?", "a": "The company is over-capitalised", "b": "The company is effectively borrowing, or drawing down cash, to pay its dividend, since operations alone don't cover it", "c": "The dividend is too small", "d": "Nothing of analytical significance", "answer": "b", "explanation": "Below 1x means operating cash flow alone is insufficient to fund the declared dividend.", "difficulty": "Medium"},
    {"chapter": "Cash Flow Ratios & Glossary", "chapter_num": 8, "question": "What does 'FCF' stand for and mean, per the glossary?", "a": "Fixed Capital Fund -- money reserved for equipment", "b": "Free Cash Flow -- operating cash flow less capex, what is genuinely available to owners", "c": "Final Cost Figure -- the last line of the income statement", "d": "Fiscal Cash Flow -- government tax receipts", "answer": "b", "explanation": "FCF = OCF less capex, representing cash genuinely available to the company's owners.", "difficulty": "Easy"},
    {"chapter": "Cash Flow Ratios & Glossary", "chapter_num": 8, "question": "According to the 'Ratios That Need Two Statements' slide, which ratio is described as 'the single best fraud screen'?", "a": "Price-to-book", "b": "Return on equity", "c": "The accruals ratio, (PAT minus OCF) divided by PAT", "d": "Cash dividend cover", "answer": "c", "explanation": "A high and rising accruals ratio signals profit made of promises rather than real cash -- the best fraud screen among the six ratios.", "difficulty": "Hard"},
]

BALANCE_SHEET_QUESTIONS = [
    # Chapter 1: What the Balance Sheet Is & The Accounting Equation
    {"chapter": "What the Balance Sheet Is & The Accounting Equation", "chapter_num": 1, "question": "The balance sheet is also known as the -", "a": "Statement of Comprehensive Income", "b": "Statement of Financial Position", "c": "Statement of Cash Flows", "d": "Statement of Retained Earnings", "answer": "b", "explanation": "The balance sheet's formal name is the Statement of Financial Position.", "difficulty": "Easy"},
    {"chapter": "What the Balance Sheet Is & The Accounting Equation", "chapter_num": 1, "question": "Unlike the income statement and cash flow statement, the balance sheet covers -", "a": "a period of twelve months", "b": "a single moment in time, e.g. 31 December 2025", "c": "a five-year rolling average", "d": "the date of the AGM only", "answer": "b", "explanation": "The balance sheet is a snapshot at one MOMENT, not a period.", "difficulty": "Easy"},
    {"chapter": "What the Balance Sheet Is & The Accounting Equation", "chapter_num": 1, "question": "The fundamental accounting equation states that -", "a": "Assets = Liabilities minus Equity", "b": "Assets = Liabilities plus Equity", "c": "Assets plus Liabilities = Equity", "d": "Equity = Assets plus Liabilities", "answer": "b", "explanation": "Assets = Liabilities + Equity is the equation that can never be broken.", "difficulty": "Easy"},
    {"chapter": "What the Balance Sheet Is & The Accounting Equation", "chapter_num": 1, "question": "At 31 December 2025, MTN's balance sheet showed Assets of GHS 62,391,057k. What were total Liabilities and Equity?", "a": "Liabilities GHS 48,219,171k + Equity GHS 14,171,886k", "b": "Liabilities GHS 14,171,886k + Equity GHS 48,219,171k", "c": "Liabilities GHS 62,391,057k + Equity zero", "d": "Liabilities GHS 24,430,308k + Equity GHS 38,392,517k", "answer": "a", "explanation": "62,391,057 = 48,219,171 (Liabilities) + 14,171,886 (Equity).", "difficulty": "Medium"},
    {"chapter": "What the Balance Sheet Is & The Accounting Equation", "chapter_num": 1, "question": "Why does the masterclass insist the accounting equation can never fail to balance?", "a": "It is enforced by the SEC as a regulatory rule", "b": "It is a tautology -- every cedi of value a company controls was funded either by a lender (liability) or an owner/retained profit (equity)", "c": "Auditors manually force it to balance every year", "d": "It only applies to telecom companies", "answer": "b", "explanation": "Every cedi arrived from somewhere -- either lent (liability) or provided/earned by owners (equity).", "difficulty": "Medium"},
    {"chapter": "What the Balance Sheet Is & The Accounting Equation", "chapter_num": 1, "question": "If a balance sheet does not balance, what does the masterclass say this means?", "a": "The company has discovered a new kind of business", "b": "Someone has made an error", "c": "The company is unusually profitable", "d": "IFRS allows a small margin of error", "answer": "b", "explanation": "If your balance sheet does not balance, you have not found a new kind of business -- you have made an error.", "difficulty": "Easy"},

    # Chapter 2: The MoMo Float
    {"chapter": "The MoMo Float", "chapter_num": 2, "question": "What is the 'MoMo float' on MTN's balance sheet?", "a": "MTN's own retained cash reserves", "b": "Cash sitting in customers' mobile money wallets, held by MTN as custodian", "c": "A financing facility provided by MTN Group", "d": "A pension fund reserve", "answer": "b", "explanation": "The float is customer money that MTN holds in trust, not its own funds.", "difficulty": "Medium"},
    {"chapter": "The MoMo Float", "chapter_num": 2, "question": "MTN's mobile money float at 31 December 2025 was -", "a": "GHS 24,000,000k", "b": "GHS 9,826,654k", "c": "GHS 38,392,517k", "d": "GHS 4,298,477k", "answer": "c", "explanation": "The mobile money float was GHS 38,392,517k, matched exactly by an equal liability to e-money holders.", "difficulty": "Medium"},
    {"chapter": "The MoMo Float", "chapter_num": 2, "question": "What is the net effect of the MoMo float on MTN's own balance sheet, once the matching liability is considered?", "a": "It adds GHS 38.39BN to MTN's real wealth", "b": "Zero -- it cancels out, because MTN owes the identical amount back to e-money holders", "c": "It is a permanent loss for MTN", "d": "It doubles MTN's equity", "answer": "b", "explanation": "The float asset and the identical obligation to e-money holders cancel out; MTN is a custodian, not an owner, of this money.", "difficulty": "Medium"},
    {"chapter": "The MoMo Float", "chapter_num": 2, "question": "According to the masterclass, what does a 'beginner' wrongly conclude from MTN's GHS 62.4BN of reported assets?", "a": "That it is broadly in line with peer telecoms", "b": "That MTN is enormous -- bigger than most Ghanaian banks -- without realising 61.5% of those 'assets' belong to MoMo customers", "c": "That MTN has too few assets", "d": "That MTN is under-capitalised", "answer": "b", "explanation": "A beginner is fooled by the headline asset figure without stripping out the float that isn't MTN's money.", "difficulty": "Medium"},
    {"chapter": "The MoMo Float", "chapter_num": 2, "question": "After stripping the MoMo float, what is MTN's approximate 'real' balance sheet size?", "a": "GHS 62.4BN of assets against GHS 48.2BN of liabilities", "b": "GHS 24.0BN of assets against GHS 9.83BN of liabilities", "c": "GHS 38.4BN of assets against GHS 38.4BN of liabilities", "d": "GHS 14.2BN of assets against zero liabilities", "answer": "b", "explanation": "Strip the float and MTN's real balance sheet is roughly GHS 24.0BN of assets against GHS 9.83BN of liabilities.", "difficulty": "Hard"},
    {"chapter": "The MoMo Float", "chapter_num": 2, "question": "Why does IFRS require MTN to show the MoMo float as both an asset AND a liability, even though it isn't MTN's own money?", "a": "IFRS ignores custodial arrangements entirely", "b": "Because MTN legally controls the asset, even though it must hand it back, so both the asset and matching obligation must be shown", "c": "It is optional disclosure that MTN chose to make", "d": "Regulators require overstatement of telecom assets", "answer": "b", "explanation": "IFRS requires showing both sides when a company controls an asset it must hand back to its rightful owner.", "difficulty": "Hard"},
    {"chapter": "The MoMo Float", "chapter_num": 2, "question": "The scale of the MoMo float is given as one reason why MTN separated which business into its own licensed entity?", "a": "The tower infrastructure business", "b": "MobileMoney Limited (MMFL)", "c": "The device retail business", "d": "The international roaming business", "answer": "b", "explanation": "A GHS 38BN fintech balance sheet was swallowing a GHS 24BN telecom, prompting MMFL's separation.", "difficulty": "Medium"},

    # Chapter 3: Non-Current Assets
    {"chapter": "Non-Current Assets", "chapter_num": 3, "question": "'Non-current assets' means assets that -", "a": "will be converted to cash within 12 months", "b": "will still be here in more than a year", "c": "have no resale value", "d": "are held only for short-term trading", "answer": "b", "explanation": "Non-current simply means the asset will still be here in more than a year.", "difficulty": "Easy"},
    {"chapter": "Non-Current Assets", "chapter_num": 3, "question": "MTN's Property, Plant and Equipment (PPE) at 31 December 2025, net of accumulated depreciation, was -", "a": "GHS 8,128,597k", "b": "GHS 10,704,580k", "c": "GHS 2,978,529k", "d": "GHS 2,422,781k", "answer": "b", "explanation": "PPE stood at GHS 10,704,580k at 31 December 2025, up from GHS 8,128,597k in 2024.", "difficulty": "Medium"},
    {"chapter": "Non-Current Assets", "chapter_num": 3, "question": "What does 'Right-of-use assets' represent on MTN's balance sheet under IFRS 16?", "a": "Assets MTN owns outright", "b": "Leased tower sites, shown as an asset because MTN controls them for years even though it rents them", "c": "Spectrum licences", "d": "Customer receivables", "answer": "b", "explanation": "IFRS 16 requires leased assets controlled for years to be shown on the balance sheet as if owned.", "difficulty": "Medium"},
    {"chapter": "Non-Current Assets", "chapter_num": 3, "question": "MTN's Intangible assets (spectrum licences and software) at 31 December 2025 were -", "a": "GHS 306,596k", "b": "GHS 10,704,580k", "c": "GHS 2,422,781k", "d": "GHS 2,978,529k", "answer": "c", "explanation": "Intangible assets were GHS 2,422,781k, up from GHS 1,734,116k in 2024.", "difficulty": "Medium"},
    {"chapter": "Non-Current Assets", "chapter_num": 3, "question": "MTN's PPE rose from GHS 8,128,597k (2024) to GHS 10,704,580k (2025), an increase of about GHS 2.58BN. This increase reflects -", "a": "GHS 6.41BN of capex additions less GHS 2.73BN of depreciation, plus lease and FX effects", "b": "a one-off revaluation gain only", "c": "a currency translation adjustment only", "d": "new borrowings raised during the year", "answer": "a", "explanation": "Additions less D&A, plus lease and FX effects, reconcile the net movement in PPE.", "difficulty": "Hard"},
    {"chapter": "Non-Current Assets", "chapter_num": 3, "question": "MTN's total non-current assets at 31 December 2025 were -", "a": "GHS 45,978,571k", "b": "GHS 62,391,057k", "c": "GHS 16,412,486k", "d": "GHS 38,392,517k", "answer": "c", "explanation": "Total non-current assets (PPE + ROU + intangibles + other) were GHS 16,412,486k.", "difficulty": "Medium"},

    # Chapter 4: Current Assets
    {"chapter": "Current Assets", "chapter_num": 4, "question": "Of MTN's total current assets of GHS 45,978,571k at 31 December 2025, how much was genuinely MTN's own money (excluding the MoMo float)?", "a": "GHS 38,392,517k", "b": "GHS 7,586,054k", "c": "GHS 4,298,477k", "d": "GHS 3,287,577k", "answer": "b", "explanation": "Only GHS 7,586,054k (cash plus other current assets) was genuinely MTN's own; the rest was the customer float.", "difficulty": "Medium"},
    {"chapter": "Current Assets", "chapter_num": 4, "question": "MTN's cash and cash equivalents at 31 December 2025 (GHS 4,298,477k) should match which other figure exactly?", "a": "The mobile money float", "b": "Total current assets", "c": "The closing cash balance on the cash flow statement", "d": "Total equity", "answer": "c", "explanation": "The balance sheet's cash line and the cash flow statement's closing cash balance must be identical -- Link 4.", "difficulty": "Medium"},
    {"chapter": "Current Assets", "chapter_num": 4, "question": "'Other current assets' of GHS 3,287,577k for MTN at 31 December 2025 included -", "a": "only the MoMo float", "b": "trade receivables, inventory, prepayments and a current tax asset (GHS 1,170,834k of which is a GRA credit)", "c": "only PPE", "d": "only intangible assets", "answer": "b", "explanation": "Other current assets is a mixed bucket including receivables, inventory, prepayments and the current tax asset.", "difficulty": "Medium"},
    {"chapter": "Current Assets", "chapter_num": 4, "question": "The receivables impairment provision rose from GHS 120,640k to GHS 253,871k. Why does the masterclass flag this as a warning sign despite being small (about 1% of revenue)?", "a": "It means overall revenue is falling", "b": "The direction/trend matters -- it means MTN increasingly expects more customers not to pay", "c": "It means MTN is currently being audited by the GRA", "d": "It has no analytical significance at all", "answer": "b", "explanation": "A provision that more than doubles is no longer small in trend, even if small in absolute terms.", "difficulty": "Hard"},
    {"chapter": "Current Assets", "chapter_num": 4, "question": "MTN's total current assets at 31 December 2025 were reported as -", "a": "GHS 16,412,486k", "b": "GHS 45,978,571k", "c": "GHS 62,391,057k", "d": "GHS 9,826,654k", "answer": "b", "explanation": "Total current assets, dominated by the MoMo float, were GHS 45,978,571k.", "difficulty": "Medium"},
    {"chapter": "Current Assets", "chapter_num": 4, "question": "Which single item makes up the vast majority of MTN's reported current assets?", "a": "Cash and cash equivalents", "b": "The mobile money float", "c": "Trade receivables", "d": "Inventory", "answer": "b", "explanation": "The mobile money float (GHS 38,392,517k) dominates the GHS 45,978,571k of total current assets.", "difficulty": "Medium"},

    # Chapter 5: Liabilities
    {"chapter": "Liabilities", "chapter_num": 5, "question": "MTN's total reported liabilities at 31 December 2025 were -", "a": "GHS 9,826,654k", "b": "GHS 48,219,171k", "c": "GHS 14,171,886k", "d": "GHS 62,391,057k", "answer": "b", "explanation": "Total liabilities as reported were GHS 48,219,171k, dominated by obligations to e-money holders.", "difficulty": "Medium"},
    {"chapter": "Liabilities", "chapter_num": 5, "question": "After stripping out obligations to e-money holders (GHS 38,392,517k), MTN's 'real' liabilities at 31 December 2025 were approximately -", "a": "GHS 9,826,654k", "b": "GHS 48,219,171k", "c": "GHS 24,000,000k", "d": "GHS 38,392,517k", "answer": "a", "explanation": "48,219,171 minus 38,392,517 gives real liabilities of GHS 9,826,654k.", "difficulty": "Medium"},
    {"chapter": "Liabilities", "chapter_num": 5, "question": "What were MTN's total borrowings at 31 December 2025?", "a": "GHS 70,443k", "b": "GHS 780,600k", "c": "Zero", "d": "GHS 9,826,654k", "answer": "c", "explanation": "MTN repaid its last GHS 70,443k of borrowings during the year, ending 2025 completely debt-free.", "difficulty": "Medium"},
    {"chapter": "Liabilities", "chapter_num": 5, "question": "MTN's loan covenants (net debt/EBITDA below 2.5x, net debt/equity within 30/70, interest cover above 4.5x, debt service cover above 1.5x) are described in the masterclass as -", "a": "breached and a major current risk", "b": "academic and irrelevant, since MTN has zero borrowings and a net cash position", "c": "about to be renegotiated with lenders", "d": "applicable only to MMFL, not Scancom PLC", "answer": "b", "explanation": "With zero borrowings and GHS 4.30BN of cash, every covenant is comfortably academic.", "difficulty": "Medium"},
    {"chapter": "Liabilities", "chapter_num": 5, "question": "MTN's 'real liabilities' (ex-float) of GHS 9,826,654k are mostly made up of -", "a": "bank loans", "b": "lease liabilities, trade payables, tax and provisions -- operating obligations, not financing debt", "c": "shareholder loans", "d": "government grants", "answer": "b", "explanation": "Real liabilities reflect operating obligations like leases, payables, tax and provisions -- not bank financing.", "difficulty": "Medium"},
    {"chapter": "Liabilities", "chapter_num": 5, "question": "What was MTN's net cash position (cash minus borrowings) at 31 December 2025?", "a": "GHS 0", "b": "GHS 4,298,477k", "c": "GHS 9,826,654k", "d": "GHS 48,219,171k", "answer": "b", "explanation": "With zero borrowings and GHS 4,298,477k of cash, MTN's net cash position equals its full cash balance.", "difficulty": "Medium"},
    {"chapter": "Liabilities", "chapter_num": 5, "question": "MTN's real liabilities (ex-float) grew from GHS 8,023,253k (2024) to GHS 9,826,654k (2025). What best explains this given borrowings fell to zero?", "a": "A rise in bank debt", "b": "Growth in operating obligations such as lease liabilities, trade payables, tax and provisions, unrelated to bank financing", "c": "A new share issue", "d": "The MoMo float increasing", "answer": "b", "explanation": "Since borrowings actually fell to zero, the growth in real liabilities came from operating items, not financing debt.", "difficulty": "Hard"},

    # Chapter 6: Equity
    {"chapter": "Equity", "chapter_num": 6, "question": "MTN's total equity at 31 December 2025 was -", "a": "GHS 48,219,171k", "b": "GHS 62,391,057k", "c": "GHS 14,171,886k", "d": "GHS 9,826,654k", "answer": "c", "explanation": "Total equity -- shareholders' residual claim -- was GHS 14,171,886k.", "difficulty": "Easy"},
    {"chapter": "Equity", "chapter_num": 6, "question": "MTN's 'Stated capital' of GHS 2,222,888k represents -", "a": "accumulated retained profits", "b": "money actually paid in by shareholders at the 2018 IPO and through scrip dividends, unchanged since 2023", "c": "a bank loan converted to equity", "d": "the value of the MoMo float", "answer": "b", "explanation": "Stated capital is the actual cash shareholders contributed, distinct from profits the company has earned and kept.", "difficulty": "Medium"},
    {"chapter": "Equity", "chapter_num": 6, "question": "What proportion of MTN's total equity at 31 December 2025 was made up of retained income (earned and kept, rather than contributed by investors)?", "a": "About 20%", "b": "About 50%", "c": "About 80%", "d": "100%", "answer": "c", "explanation": "Retained income of GHS 11,304,442k is about 80% of total equity of GHS 14,171,886k.", "difficulty": "Medium"},
    {"chapter": "Equity", "chapter_num": 6, "question": "MTN's retained income at 31 December 2025 was -", "a": "GHS 2,222,888k", "b": "GHS 629,903k", "c": "GHS 11,304,442k", "d": "GHS 14,171,886k", "answer": "c", "explanation": "Retained income was GHS 11,304,442k, up from GHS 7,992,987k in 2024.", "difficulty": "Medium"},
    {"chapter": "Equity", "chapter_num": 6, "question": "What new equity reserve line appeared on MTN's balance sheet for the first time in 2025?", "a": "Other reserves", "b": "Stated capital", "c": "Integrity capital reserve", "d": "Contract liabilities", "answer": "c", "explanation": "The Integrity capital reserve (GHS 14,653k) is a new line in 2025, with no 2024 comparative.", "difficulty": "Medium"},
    {"chapter": "Equity", "chapter_num": 6, "question": "MTN's book value per share at 31 December 2025 (total equity divided by shares in issue) was approximately -", "a": "GHS 0.592", "b": "GHS 1.07", "c": "GHS 6.44", "d": "GHS 6.0", "answer": "b", "explanation": "Book value per share = GHS 14,171,886k / 13.24BN shares ≈ GHS 1.07.", "difficulty": "Medium"},
    {"chapter": "Equity", "chapter_num": 6, "question": "With a market price of GHS 6.44 and a book value per share of GHS 1.07, MTN's price-to-book ratio was approximately -", "a": "1.07x", "b": "0.17x", "c": "6.0x", "d": "10.9x", "answer": "c", "explanation": "Price-to-book = 6.44 / 1.07 ≈ 6.0x, reflecting the value of the brand, licence and subscriber base.", "difficulty": "Medium"},

    # Chapter 7: Interconnections -- Retained Income & Cash Identity
    {"chapter": "Interconnections: Retained Income & Cash Identity", "chapter_num": 7, "question": "Link 1, the 'master link', shows how retained income moves each year using which formula?", "a": "Opening retained income + Revenue - Cost of sales = Closing retained income", "b": "Opening retained income + Profit after tax - Dividends paid = Closing retained income", "c": "Opening retained income + Capex - D&A = Closing retained income", "d": "Opening retained income + Cash - Liabilities = Closing retained income", "answer": "b", "explanation": "Retained income rolls forward by adding PAT and subtracting dividends paid.", "difficulty": "Medium"},
    {"chapter": "Interconnections: Retained Income & Cash Identity", "chapter_num": 7, "question": "Applying Link 1 to MTN's FY2025 figures: Opening retained income GHS 7,992,987k + PAT GHS 7,839,930k minus Dividends GHS 4,528,475k equals a closing retained income of -", "a": "GHS 11,304,442k", "b": "GHS 14,171,886k", "c": "GHS 3,311,455k", "d": "GHS 20,161,392k", "answer": "a", "explanation": "7,992,987 + 7,839,930 - 4,528,475 = 11,304,442, matching the reported closing retained income exactly.", "difficulty": "Medium"},
    {"chapter": "Interconnections: Retained Income & Cash Identity", "chapter_num": 7, "question": "Link 4 states that the closing cash balance on the cash flow statement must equal -", "a": "total equity", "b": "the cash and cash equivalents line on the balance sheet -- exactly, with no tolerance", "c": "EBITDA", "d": "total assets", "answer": "b", "explanation": "Cash flow closing cash and balance sheet cash are an identity -- they must match exactly.", "difficulty": "Medium"},
    {"chapter": "Interconnections: Retained Income & Cash Identity", "chapter_num": 7, "question": "What does the masterclass say it means if the cash flow statement's closing cash and the balance sheet's cash figure ever differ?", "a": "This is normal and expected variance", "b": "Someone has made an error, or is committing fraud -- there is no third possibility", "c": "It only happens for companies with leases", "d": "It reflects foreign currency translation timing", "answer": "b", "explanation": "This is the first check any auditor runs, and the first check any analyst should run too.", "difficulty": "Medium"},
    {"chapter": "Interconnections: Retained Income & Cash Identity", "chapter_num": 7, "question": "In Link 2 ('one number, three jobs'), MTN's depreciation of GHS 2,322,138k does what on the balance sheet?", "a": "Increases cash directly", "b": "Reduces the carrying value of PPE, via accumulated depreciation", "c": "Increases retained income", "d": "Increases the MoMo float", "answer": "b", "explanation": "On the balance sheet, accumulated depreciation reduces the carrying (net) value of PPE.", "difficulty": "Medium"},
    {"chapter": "Interconnections: Retained Income & Cash Identity", "chapter_num": 7, "question": "Despite GHS 2.32BN of depreciation 'wearing down' assets in 2025, why did MTN's PPE still rise to GHS 10,704,580k?", "a": "A one-off revaluation was applied", "b": "Capex additions outpaced depreciation, roughly 2.35 times over", "c": "Depreciation was reversed at year end", "d": "PPE excludes depreciation entirely by definition", "answer": "b", "explanation": "The capex-to-D&A ratio of 2.35x means the business is still building, not just replacing what wears out.", "difficulty": "Hard"},

    # Chapter 8: Interconnections -- Where Differences Live & Ratios
    {"chapter": "Interconnections: Where Differences Live & Ratios", "chapter_num": 8, "question": "Link 5 shows the income statement's tax CHARGE (GHS 2,906,475k) differs from cash tax PAID (GHS 3,394,101k). Where does this GHS 487,626k difference 'park' on the balance sheet?", "a": "Trade payables", "b": "A current tax asset of GHS 1,170,834k", "c": "Retained income", "d": "The MoMo float", "answer": "b", "explanation": "Every difference between profit and cash has a home -- here, it parks as a current tax asset.", "difficulty": "Hard"},
    {"chapter": "Interconnections: Where Differences Live & Ratios", "chapter_num": 8, "question": "Per Link 6, a rise in trade receivables (revenue booked but not yet collected) shows up on the balance sheet as -", "a": "an increase in trade payables", "b": "an increase in trade receivables, with a matching impairment provision", "c": "a reduction in retained income", "d": "an increase in the MoMo float", "answer": "b", "explanation": "Uncollected revenue sits as trade receivables on the balance sheet, alongside its impairment provision.", "difficulty": "Medium"},
    {"chapter": "Interconnections: Where Differences Live & Ratios", "chapter_num": 8, "question": "Per Link 6, cash collected before a service is delivered (e.g. unused prepaid airtime) shows up on the balance sheet as -", "a": "trade receivables", "b": "contract liabilities", "c": "PPE", "d": "stated capital", "answer": "b", "explanation": "Cash received without matching revenue recognised sits as a contract liability until the service is delivered.", "difficulty": "Medium"},
    {"chapter": "Interconnections: Where Differences Live & Ratios", "chapter_num": 8, "question": "Combined, MTN's PPE, right-of-use assets and intangible assets at 31 December 2025 totalled approximately -", "a": "GHS 9,826,654k", "b": "GHS 16,105,890k", "c": "GHS 45,978,571k", "d": "GHS 38,392,517k", "answer": "b", "explanation": "10,704,580 + 2,978,529 + 2,422,781 = GHS 16,105,890k of cash spent on assets not yet fully expensed.", "difficulty": "Hard"},
    {"chapter": "Interconnections: Where Differences Live & Ratios", "chapter_num": 8, "question": "MTN's Return on Equity (PAT divided by Equity) for FY2025, one of the 'ratios that need two statements' (income statement over balance sheet), was approximately -", "a": "12.3%", "b": "32.1%", "c": "55.3%", "d": "6.0%", "answer": "c", "explanation": "ROE = 7,839,930 / 14,171,886 ≈ 55.3%, described in the masterclass as exceptional.", "difficulty": "Medium"},
]
