"""Add youtube_link to Article

Revision ID: 720742ece185
Revises: cd73eb0321fd
Create Date: 2025-06-15 09:55:30.526551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '720742ece185'
down_revision = 'cd73eb0321fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtube_link', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('youtube_link')

    # ### end Alembic commands ###
